"""End-to-end smoke test against a real Linear workspace (linear-007).

V1 Definition-of-Done validation: this is the only test in the suite that
hits the live Linear API. It is gated on two env vars so the test silently
skips on every CI run / local dev pass that doesn't have credentials:

  TASKMASTER_LINEAR_SMOKE_TOKEN  — Linear personal API key
  TASKMASTER_LINEAR_SMOKE_TEAM   — Linear team UUID (not the team key)

To run locally:

  $env:TASKMASTER_LINEAR_SMOKE_TOKEN = "lin_api_xxx"
  $env:TASKMASTER_LINEAR_SMOKE_TEAM  = "team-uuid-from-list_teams"
  python -m pytest plugins/taskmaster/tests/test_linear_smoke.py -v -s

The test creates a real issue in the target Linear team, mutates it once
to exercise the push_hash skip path, then prints the resulting issue
identifier so the operator can clean it up manually. We deliberately do
NOT auto-delete it — Linear has no hard-delete for issues, and the
soft-delete (archive) requires a different mutation; leaving manual
cleanup keeps this test free of state-mutating surface beyond the push
path itself.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest
import yaml

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PLUGIN_ROOT))

from integrations.linear.client import LinearClient  # noqa: E402
from integrations.linear.worker import drain, enqueue, read_queue  # noqa: E402
from taskmaster_v3 import write_tracker, read_tracker  # noqa: E402


SMOKE_TOKEN = os.environ.get("TASKMASTER_LINEAR_SMOKE_TOKEN")
SMOKE_TEAM = os.environ.get("TASKMASTER_LINEAR_SMOKE_TEAM")

pytestmark = pytest.mark.skipif(
    not (SMOKE_TOKEN and SMOKE_TEAM),
    reason="Linear smoke test requires TASKMASTER_LINEAR_SMOKE_TOKEN + TASKMASTER_LINEAR_SMOKE_TEAM",
)


def _build_backlog(tmp_path: Path, task_id: str, tracker_id: str | None) -> Path:
    bp = tmp_path / "backlog.yaml"
    task = {
        "id": task_id,
        "title": f"TM smoke test [{task_id}]",
        "status": "in-progress",
        "priority": "high",
        "owner": "smoke",
        "tags": ["smoke", "auto-generated"],
        "tldr": "Auto-generated by linear-007 smoke test; safe to archive.",
        "notes": "",
    }
    if tracker_id:
        task["tracker_id"] = tracker_id
    bp.write_text(yaml.safe_dump({
        "meta": {"updated": "2026-05-21"},
        "epics": [{"id": "smoke", "name": "Smoke", "tasks": [task]}],
        "phases": [],
    }))
    return bp


def test_smoke_full_push_round_trip(tmp_path, capsys):
    """Probe + create + push + push_hash skip, end to end against real Linear."""
    client = LinearClient(token=SMOKE_TOKEN)

    teams = client.list_teams()
    target = next((t for t in teams if t.get("id") == SMOKE_TEAM), None)
    assert target, (
        f"TASKMASTER_LINEAR_SMOKE_TEAM={SMOKE_TEAM!r} not found in workspace "
        f"(saw {[t.get('key') for t in teams]})"
    )

    statuses = client.list_issue_statuses(SMOKE_TEAM)
    in_progress = next((s for s in statuses if "progress" in (s.get("name") or "").lower()), None)
    assert in_progress, f"no 'In Progress'-shaped state in team {target.get('key')!r}: {[s.get('name') for s in statuses]}"

    config = {
        "workspaces": [{
            "alias": "smoke",
            "team_id": SMOKE_TEAM,
            "token_env": "TASKMASTER_LINEAR_SMOKE_TOKEN",
            "status_mapping": {"in-progress": in_progress["id"]},
            "priority_mapping": {"high": 2},
        }],
        "default_workspace": "smoke",
    }

    task_id = "smoke-001"
    bp = _build_backlog(tmp_path, task_id=task_id, tracker_id=None)

    issue_title = f"TM smoke test [{task_id}]"
    created = client.issue_upsert(SMOKE_TEAM, {
        "title": issue_title,
        "description": "Created by linear-007 smoke test. Safe to archive.",
        "stateId": in_progress["id"],
        "priority": 2,
    })
    assert created.get("identifier"), f"issue creation returned no identifier: {created!r}"
    linear_key = created["identifier"]
    linear_id = created["id"]
    print(f"\n[smoke] created Linear issue {linear_key} ({linear_id}) — archive after run")

    tracker_id = f"linear-smoke-{linear_key.lower()}"
    write_tracker(
        bp,
        external_system="linear",
        instance_alias="smoke",
        external_key=linear_key,
        title=issue_title,
        status="in-progress",
        url=f"https://linear.app/issue/{linear_key}",
    )

    data = yaml.safe_load(bp.read_text())
    data["epics"][0]["tasks"][0]["tracker_id"] = tracker_id
    bp.write_text(yaml.safe_dump(data))

    enqueue(bp, op="task_upsert", target_id=task_id, tracker_id=tracker_id)
    assert len(read_queue(bp)) == 1

    backlog_data = yaml.safe_load(bp.read_text())
    counts = drain(bp, client, config, backlog_data=backlog_data)
    assert counts.get("ok") == 1, f"first drain expected ok=1, got {counts!r}"
    assert read_queue(bp) == []

    tracker_fm, _ = read_tracker(bp, tracker_id)
    assert tracker_fm.get("last_pushed"), "tracker did not record last_pushed after successful push"
    assert tracker_fm.get("push_hash"), "tracker did not record push_hash after successful push"
    first_hash = tracker_fm["push_hash"]

    enqueue(bp, op="task_upsert", target_id=task_id, tracker_id=tracker_id)
    counts2 = drain(bp, client, config, backlog_data=backlog_data)
    assert counts2.get("skipped") == 1, (
        f"second drain should hit the push_hash skip (unchanged state), got {counts2!r}"
    )

    tracker_after, _ = read_tracker(bp, tracker_id)
    assert tracker_after["push_hash"] == first_hash, "push_hash drifted across no-op drain"

    captured = capsys.readouterr()
    assert linear_key in captured.out
