"""User intent: prove every remaining N02 mutating family commits through the
native core — task lifecycle, gates, claims, epic/phase transitions, promotion,
typed links, settings and the Linear outbox — in one transaction each, with the
domain rules and the queue/graph selectivity the legacy tools guarantee.
"""
import ast
from contextlib import closing
import re
import json
from pathlib import Path
import sqlite3

import pytest

from taskmaster.native.commands import execute, Conflict
from taskmaster.native.queries import Repository
from taskmaster.native.workflow import _bugs_found_in
from test_native_commands import native, envelope  # noqa: F401
from test_native_migration import legacy  # noqa: F401


def run(connection, operation, arguments, key):
    return execute(connection, envelope(operation, arguments, key=key))


def created(connection, operation, arguments, key):
    return run(connection, operation, arguments, key)["affected"][0]["id"]


@pytest.fixture
def workspace(native):
    """A native store carrying one area, epic, phase and two todo tasks."""
    with closing(sqlite3.connect(native, isolation_level=None)) as connection:
        connection.execute("INSERT INTO id_counters VALUES('issue','ISS-',0)")
        connection.execute("INSERT INTO id_counters VALUES('bug','B-',1)")
        run(connection, "area.create", {"area_id": "viewer", "name": "Viewer"}, "area")
        run(connection, "phase.create", {"phase_id": "foundation", "name": "Foundation"}, "phase")
        run(connection, "epic.create", {"epic_id": "demo", "name": "Demo", "done_when": "shipped",
                                        "area": "viewer"}, "epic")
        run(connection, "task.create", {"title": "First", "epic": "demo", "phase": "foundation",
                                        "priority": "low"}, "first")
        run(connection, "task.create", {"title": "Second", "epic": "demo", "phase": "foundation",
                                        "priority": "low"}, "second")
    return native


def _queued(connection, target_id):
    return connection.execute("SELECT op,target_id,tracker_id,state FROM linear_queue "
                              "WHERE target_id=?", (target_id,)).fetchall()


def express(connection, ident, key):
    """Put a task on the shortest lane and satisfy it, so completion is legal."""
    run(connection, "task.update", {"id": ident, "field": "lane", "value": "express"}, f"lane-{key}")
    run(connection, "task.gate", {"id": ident, "gate": "review-gate", "verdict": "pass"}, f"gate-{key}")


def fields(connection, kind, ident):
    with Repository(connection).snapshot() as query:
        return query.get(kind, ident)["fields"]


# ── Task creation, identity and ordering ────────────────────────────────────


def test_task_ids_are_allocated_per_epic_and_never_recycled(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        assert [row[0] for row in connection.execute(
            "SELECT public_id FROM entity_core WHERE kind='task' AND public_id LIKE 'demo-%' ORDER BY public_id")] \
            == ["demo-001", "demo-002"]
        assert fields(connection, "task", "demo-002")["order"] == 2.0
        # A reserved id is never handed out a second time, even after removal.
        connection.execute("BEGIN IMMEDIATE")
        connection.execute("DELETE FROM entity_core WHERE kind='task' AND public_id='demo-002'")
        connection.commit()
        assert created(connection, "task.create", {"title": "Third", "epic": "demo",
                                                   "phase": "foundation"}, "third") == "demo-003"


def test_task_create_derives_lane_gate_state_and_autogenerated_tldr(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        ident = created(connection, "task.create",
                        {"title": "Critical work", "epic": "demo", "phase": "foundation",
                         "priority": "critical", "notes": "Because the loader crashes."}, "hot")
        stored = fields(connection, "task", ident)
        assert stored["lane"] == "full"
        assert stored["gate_state"] == "spec-review:pending"
        assert stored["tldr_autogen"] is True and stored["tldr"]


@pytest.mark.parametrize("arguments", [
    {"title": "X", "epic": "absent", "phase": "foundation"},
    {"title": "X", "epic": "demo", "phase": "absent"},
    {"title": "X", "epic": "demo", "phase": "foundation", "depends_on": ["absent"]},
    {"title": "X", "epic": "demo", "phase": "foundation", "area": "absent"},
])
def test_task_create_rolls_back_every_unresolved_reference(workspace, arguments):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        before = connection.execute("SELECT COUNT(*) FROM entity_core").fetchone()[0]
        with pytest.raises(KeyError):
            run(connection, "task.create", arguments, "bad")
        assert connection.execute("SELECT COUNT(*) FROM entity_core").fetchone()[0] == before
        assert connection.execute("SELECT COUNT(*) FROM id_reservations WHERE public_id='demo-003'").fetchone()[0] == 0


# ── Claims and pick eligibility ─────────────────────────────────────────────


def test_claim_is_exclusive_until_a_caller_forces_it(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        assert fields(connection, "task", "demo-001")["locked_by"] == "alpha"
        with pytest.raises(Conflict, match="locked by another session"):
            run(connection, "task.pick", {"id": "demo-001", "session": "beta"}, "steal")
        run(connection, "task.pick", {"id": "demo-001", "session": "beta", "force": True}, "forced")
        stored = fields(connection, "task", "demo-001")
        assert stored["locked_by"] == "beta" and stored["status"] == "in-progress"


def test_a_done_task_cannot_be_picked(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        run(connection, "task.update", {"id": "demo-001", "field": "lane", "value": "express"}, "lane")
        run(connection, "task.gate", {"id": "demo-001", "gate": "review-gate", "verdict": "pass"}, "gate")
        run(connection, "task.complete", {"id": "demo-001"}, "done")
        with pytest.raises(ValueError, match="expected one of"):
            run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "repick")


def test_a_malformed_bundle_is_refused_by_name_not_by_the_driver(workspace):
    """A list-valued bundle reaches the store from the legacy format. Binding it
    into SQL raised a raw driver error naming no task; the tool compares in
    Python and degrades gracefully."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        key = connection.execute(
            "SELECT entity_key FROM entity_core WHERE kind='task' AND public_id='demo-001'").fetchone()[0]
        connection.execute("INSERT INTO field_shapes VALUES(?,'bundle','list')", (key,))
        connection.execute("INSERT INTO memberships VALUES(?,'bundle',0,?,NULL,NULL,NULL,NULL)",
                           (key, '"alpha"'))
        assert fields(connection, "task", "demo-001")["bundle"] == ["alpha"]
        with pytest.raises(ValueError, match="demo-001"):
            run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")


def test_a_peers_lock_on_a_todo_row_refuses_the_pick_unless_forced(workspace):
    """The holder is `locked_by`, whatever the row's status (`native.claims`):
    `backlog_context` reports a peer's lock on a `todo` row as held, so a pick
    must not take it silently. N07 picked such a row for parity with a tool that
    only looked at the lock inside its in-progress branch; that was a silent
    steal of a claim the resolver reports. The status check still comes first."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.update", {"id": "demo-001", "field": "locked_by", "value": "ghost"}, "stale")
        assert fields(connection, "task", "demo-001")["status"] == "todo"
        with pytest.raises(Conflict, match="locked by another session"):
            run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        assert fields(connection, "task", "demo-001")["locked_by"] == "ghost"
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha", "force": True}, "steal")
        stored = fields(connection, "task", "demo-001")
        assert stored["locked_by"] == "alpha" and stored["status"] == "in-progress"


def test_a_bundle_pick_never_resurrects_an_archived_member(workspace):
    """Bundle pick is the one claim path the transition table does not guard, so
    an archived member it still counted would come back in-progress *and*
    archived at once — hidden from the board, exported to tasks/archive/, and
    holding a live session lock."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        for ident in ("demo-001", "demo-002"):
            run(connection, "task.update", {"id": ident, "field": "bundle", "value": "shared"}, f"bundle-{ident}")
        run(connection, "task.archive", {"id": "demo-002", "reason": "deprecated"}, "archive")
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        with Repository(connection).snapshot() as query:
            stale = query.get("task", "demo-002")
            assert stale["archived"]
            assert stale["fields"]["status"] == "archived"
            assert "locked_by" not in stale["fields"]
            assert query.get("task", "demo-001")["fields"]["status"] == "in-progress"


def test_an_archived_member_cannot_veto_a_bundle_sub_repo_check(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.update", {"id": "demo-002", "field": "sub_repo", "value": "other"}, "repo")
        run(connection, "task.update", {"id": "demo-002", "field": "bundle", "value": "shared"}, "bundle")
        run(connection, "task.archive", {"id": "demo-002", "reason": "deprecated"}, "archive")
        run(connection, "task.update", {"id": "demo-001", "field": "bundle", "value": "shared"}, "join")
        assert fields(connection, "task", "demo-001")["bundle"] == "shared"


def test_picking_a_bundle_member_claims_every_member_on_one_branch(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        for ident in ("demo-001", "demo-002"):
            run(connection, "task.update", {"id": ident, "field": "bundle", "value": "shared"}, f"bundle-{ident}")
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        for ident in ("demo-001", "demo-002"):
            stored = fields(connection, "task", ident)
            assert stored["status"] == "in-progress" and stored["locked_by"] == "alpha"
            assert stored["branch"] == "feature/shared" and stored["worktree"] == ".worktrees/shared"


# ── Gates, merges and spec review ───────────────────────────────────────────


def test_gate_order_is_enforced_and_gate_state_mirrors_the_pipeline(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.update", {"id": "demo-001", "field": "lane", "value": "full"}, "lane")
        with pytest.raises(ValueError, match="earlier required gate `spec-review`"):
            run(connection, "task.gate", {"id": "demo-001", "gate": "plan-review", "verdict": "pass"}, "early")
        run(connection, "task.gate", {"id": "demo-001", "gate": "spec-review", "verdict": "pass"}, "spec")
        assert fields(connection, "task", "demo-001")["gate_state"] == "plan-review:pending"
        run(connection, "task.gate", {"id": "demo-001", "gate": "plan-review", "verdict": "fail"}, "plan")
        assert fields(connection, "task", "demo-001")["gate_state"] == "blocked@plan-review"


def test_skipping_a_gate_records_the_audit_trail_and_unblocks_completion(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.update", {"id": "demo-001", "field": "lane", "value": "express"}, "lane")
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        with pytest.raises(ValueError, match="outstanding gates"):
            run(connection, "task.complete", {"id": "demo-001"}, "blocked")
        run(connection, "task.gate_skip", {"id": "demo-001", "gate": "review-gate",
                                           "reason": "trivial rename", "by": "user"}, "skip")
        record = fields(connection, "task", "demo-001")["gates"]["review-gate"]
        assert record["skipped"] is True and record["reason"] == "trivial rename" and record["by"] == "user"
        run(connection, "task.complete", {"id": "demo-001"}, "done")
        assert fields(connection, "task", "demo-001")["status"] == "done"


def test_clearing_an_absent_gate_writes_nothing(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        result = run(connection, "task.gate_clear", {"id": "demo-001", "gate": "impl"}, "clear")
        assert result["affected"] == [] and result["projection_state"] == "unchanged"


def test_spec_review_writes_both_the_gate_and_the_legacy_mirror(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.spec_review", {"id": "demo-001", "verdict": "warn",
                                             "spec_path": "docs/plans/x.md", "critical_count": 2}, "review")
        stored = fields(connection, "task", "demo-001")
        assert stored["gates"]["spec-review"]["verdict"] == "warn"
        assert stored["spec_review"]["critical_count"] == 2
        run(connection, "task.spec_review_clear", {"id": "demo-001"}, "clear")
        stored = fields(connection, "task", "demo-001")
        assert "spec-review" not in stored["gates"] and "spec_review" not in stored


def test_merge_rungs_stamp_the_ladder_state(workspace):
    targets = [{"label": "develop"}, {"label": "stage"}, {"label": "master"}]
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.merge", {"id": "demo-001", "rung": "develop", "sha": "abc1234",
                                       "merge_targets": targets}, "develop")
        run(connection, "task.merge", {"id": "demo-001", "rung": "stage", "sha": "def5678",
                                       "merge_targets": targets}, "stage")
        stored = fields(connection, "task", "demo-001")
        assert stored["merge_status"]["stage"]["merge_commit"] == "def5678"
        assert stored["merge_gate_state"] == "stage"


# ── Completion, bugs and handovers ──────────────────────────────────────────


def test_an_open_bug_naming_the_task_blocks_completion_case_insensitively(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "bug.create", {"title": "Crash", "found_in": "DEMO-001"}, "bug")
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        with pytest.raises(ValueError, match="open bug"):
            run(connection, "task.complete", {"id": "demo-001"}, "blocked")


def _hand_edit_found_in(connection, bug_id, value_json):
    """Write a `found_in` no tool can produce, as a hand-edited or imported row would."""
    connection.execute(
        "UPDATE entity_extensions SET value_json=? WHERE field='found_in' AND entity_key="
        "(SELECT entity_key FROM entity_core WHERE kind='bug' AND public_id=?)", (value_json, bug_id))


def test_a_bug_whose_found_in_is_not_a_string_refuses_rather_than_missing_the_gate(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        bug = created(connection, "bug.create", {"title": "Crash", "found_in": "demo-001"}, "bug")
        _hand_edit_found_in(connection, bug, json.dumps(["demo-001"]))
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        express(connection, "demo-001", "complete")
        with pytest.raises(ValueError, match=f"bug `{bug}` has a malformed found_in"):
            run(connection, "task.complete", {"id": "demo-001"}, "blocked")
        assert fields(connection, "task", "demo-001")["status"] == "in-progress"


def test_the_close_gate_folds_case_beyond_ascii(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        bug = created(connection, "bug.create", {"title": "Crash", "found_in": "demo-001"}, "bug")
        _hand_edit_found_in(connection, bug, json.dumps("ÉDEMO-001"))
        assert _bugs_found_in(connection, "édemo-001") == ([bug], [])


def test_completion_archives_the_bugs_the_task_fixed_in_the_same_commit(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        bug = created(connection, "bug.create", {"title": "Crash", "found_in": "demo-001"}, "bug")
        run(connection, "bug.update", {"id": bug, "patch": {"status": "fixed", "fix_commit": "abc123"}}, "fix")
        # The completing session is the holder: its own status change releases
        # the claim, where a live peer's claim would survive it.
        run(connection, "task.pick", {"id": "demo-001", "session": "tests"}, "claim")
        express(connection, "demo-001", "complete")
        receipt = run(connection, "task.complete", {"id": "demo-001", "patchnote": "Loader fixed"}, "done")
        assert {row["id"] for row in receipt["affected"]} == {"demo-001", bug}
        with Repository(connection).snapshot() as query:
            assert query.get("bug", bug)["archived"]
            task = query.get("task", "demo-001")["fields"]
        assert task["status"] == "done" and task["patchnote"] == "Loader fixed"
        assert "locked_by" not in task


def test_the_session_changelog_paragraph_commits_with_the_transition(workspace):
    def pending(connection):
        return [json.loads(value)["text"] for (value,) in connection.execute(
            "SELECT value_json FROM sync_state WHERE key LIKE 'progress.pending.%' ORDER BY key")]

    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        express(connection, "demo-001", "log")
        run(connection, "task.complete", {"id": "demo-001", "changelog": "### Session\n- shipped"}, "done")
        # One row per paragraph (N11 D4), never the pre-N11 whole-list key.
        assert pending(connection) == ["### Session\n- shipped"]
        assert connection.execute(
            "SELECT 1 FROM sync_state WHERE key='pending_progress_log'").fetchone() is None
        with pytest.raises(ValueError):
            run(connection, "task.complete", {"id": "demo-002", "changelog": "lost"}, "rejected")
        assert len(pending(connection)) == 1


def test_in_review_requires_a_human_action(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        with pytest.raises(ValueError, match="human_action"):
            run(connection, "task.complete", {"id": "demo-001", "target_status": "in-review"}, "review")
        run(connection, "task.complete", {"id": "demo-001", "target_status": "in-review",
                                          "human_action": "add the API key"}, "review2")
        assert fields(connection, "task", "demo-001")["human_action"] == "add the API key"


def test_completion_closes_the_open_handover_that_only_named_this_task(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        handover = created(connection, "handover.create",
                           {"tldr": "Wrapping demo-001", "task_ids": ["demo-001"],
                            "session_kind": "task-complete"}, "handover")
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        express(connection, "demo-001", "close")
        run(connection, "task.complete", {"id": "demo-001"}, "done")
        assert fields(connection, "handover", handover)["status"] == "closed"


def test_archiving_refuses_a_todo_task_closed_as_done_and_moves_the_projection(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        with pytest.raises(ValueError, match="todo"):
            run(connection, "task.archive", {"id": "demo-001", "reason": "done"}, "bad")
        run(connection, "task.archive", {"id": "demo-001", "reason": "deprecated"}, "archive")
        with Repository(connection).snapshot() as query:
            assert query.get("task", "demo-001")["archived"]
        jobs = connection.execute("SELECT effect,file FROM projection_jobs WHERE "
                                  "commit_seq=(SELECT MAX(seq) FROM domain_events) ORDER BY job_key").fetchall()
        assert ("delete", "tasks/demo-001.md") in jobs
        assert ("write", "tasks/archive/demo-001.md") in jobs


# ── Status transitions ──────────────────────────────────────────────────────


def test_the_transition_table_is_the_same_one_the_tools_apply(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.update", {"id": "demo-001", "field": "lane", "value": "express"}, "lane")
        with pytest.raises(ValueError, match="illegal transition"):
            run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "done"}, "jump")
        run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "in-progress"}, "start")
        assert fields(connection, "task", "demo-001")["started"]


def test_leaving_in_progress_releases_the_holders_own_claim(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.pick", {"id": "demo-001", "session": "tests"}, "claim")
        run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "blocked"}, "block")
        assert "locked_by" not in fields(connection, "task", "demo-001")


def test_leaving_in_progress_keeps_a_peers_unexpired_claim(workspace):
    """A status change by one session does not free another's work (N09 §4f)."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "blocked"}, "block")
        assert fields(connection, "task", "demo-001")["locked_by"] == "alpha"


# ── Epic and phase transitions ──────────────────────────────────────────────


def test_archiving_an_epic_cascades_to_its_live_tasks_in_one_commit(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        receipt = run(connection, "epic.archive", {"id": "demo", "reason": "superseded"}, "archive")
        assert {row["id"] for row in receipt["affected"]} == {"demo", "demo-001", "demo-002"}
        with Repository(connection).snapshot() as query:
            assert query.get("epic", "demo")["archived"]
            assert query.get("task", "demo-001")["fields"]["archive_reason"] == "superseded"
        with pytest.raises(ValueError, match="already archived"):
            run(connection, "epic.archive", {"id": "demo"}, "again")


def test_epic_status_cannot_archive_and_components_must_be_well_formed(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        with pytest.raises(ValueError, match="epic.archive"):
            run(connection, "epic.update", {"id": "demo", "field": "status", "value": "archived"}, "sneak")
        with pytest.raises(ValueError, match="unknown component"):
            run(connection, "epic.update", {"id": "demo", "field": "components",
                                            "value": json.dumps({"a": {"after": ["b"]}})}, "bad")
        run(connection, "epic.update", {"id": "demo", "field": "components",
                                        "value": json.dumps({"a": {"title": "A", "after": []}})}, "good")
        assert fields(connection, "epic", "demo")["components"] == {"a": {"title": "A", "after": []}}


def test_only_one_phase_is_active_and_advance_archives_done_tasks(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "phase.create", {"phase_id": "polish", "name": "Polish"}, "polish")
        assert fields(connection, "phase", "foundation")["status"] == "active"
        assert fields(connection, "phase", "polish")["status"] == "planned"
        run(connection, "phase.update", {"id": "foundation", "field": "deliverables",
                                         "value": json.dumps({"action": "add", "text": "ship"})}, "deliverable")
        with pytest.raises(ValueError, match="unchecked deliverable"):
            run(connection, "phase.advance", {}, "blocked")
        run(connection, "phase.update", {"id": "foundation", "field": "deliverables",
                                         "value": json.dumps({"action": "toggle", "index": 0})}, "toggle")
        run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "in-progress"}, "start")
        express(connection, "demo-001", "advance")
        run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "done"}, "finish")
        # demo-002 is still todo: the phase does not advance unless forced.
        with pytest.raises(ValueError, match="tasks in phase Foundation are not done"):
            run(connection, "phase.advance", {}, "unfinished")
        run(connection, "phase.advance", {"force": True}, "advance")
        with Repository(connection).snapshot() as query:
            assert query.get("phase", "foundation")["fields"]["status"] == "done"
            assert query.get("phase", "polish")["fields"]["status"] == "active"
            assert query.get("task", "demo-001")["archived"]
            assert not query.get("task", "demo-002")["archived"]


def test_activating_a_phase_stands_the_previous_one_down(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "phase.create", {"phase_id": "polish", "name": "Polish"}, "polish")
        run(connection, "phase.update", {"id": "polish", "field": "status", "value": "active"}, "activate")
        assert fields(connection, "phase", "foundation")["status"] == "planned"
        assert fields(connection, "phase", "polish")["start_date"]


# ── Promotion, links and auto-link ──────────────────────────────────────────


def test_bug_promotion_creates_the_issue_and_flips_every_bug_atomically(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        first = created(connection, "bug.create", {"title": "One", "components": ["loader"]}, "b1")
        second = created(connection, "bug.create", {"title": "Two", "components": ["viewer"]}, "b2")
        receipt = run(connection, "bug.promote", {"bug_ids": [first, second], "title": "Systemic loader fault",
                                                  "severity": "P1", "evidence_text": "Three reports this week"},
                      "promote")
        issue = next(row["id"] for row in receipt["affected"] if row["id"].startswith("ISS-"))
        with Repository(connection).snapshot() as query:
            assert query.get("issue", issue)["fields"]["components"] == ["loader", "viewer"]
            assert query.get("issue", issue)["fields"]["promoted_from"] == [first, second]
            for ident in (first, second):
                stored = query.get("bug", ident)["fields"]
                assert stored["status"] == "promoted" and stored["promoted_to"] == issue
        before = connection.execute("SELECT COUNT(*) FROM entity_core").fetchone()[0]
        with pytest.raises(KeyError):
            run(connection, "bug.promote", {"bug_ids": [first, "B-404"], "title": "X",
                                            "severity": "P2", "evidence_text": "y"}, "missing")
        assert connection.execute("SELECT COUNT(*) FROM entity_core").fetchone()[0] == before


def test_a_typed_link_writes_the_inverse_and_refuses_a_dependency_cycle(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        for suffix in ("1", "2"):
            run(connection, "task.create", {"title": f"Linked {suffix}", "epic": "demo",
                                            "phase": "foundation", "task_id": f"T-{suffix}"}, f"t{suffix}")
        run(connection, "link.create", {"source": "T-1", "target": "T-2", "type": "depends_on",
                                        "note": "ordering"}, "link")
        # The note is an operator annotation the tool never stored; the document
        # must keep the exact two-key link shape the round trip expects.
        assert fields(connection, "task", "T-1")["links"] == [{"type": "depends_on", "target": "T-2"}]
        assert fields(connection, "task", "T-2")["links"] == [{"type": "blocks", "target": "T-1"}]
        with pytest.raises(ValueError, match="cycle"):
            run(connection, "link.create", {"source": "T-2", "target": "T-1", "type": "depends_on"}, "cycle")
        run(connection, "link.remove", {"source": "T-1", "target": "T-2"}, "unlink")
        with Repository(connection).snapshot() as query:
            assert "links" not in query.get("task", "T-1")["fields"]
            assert "links" not in query.get("task", "T-2")["fields"]


def test_link_domains_and_unknown_targets_are_refused(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "task.create", {"title": "Prefixed", "epic": "demo", "phase": "foundation",
                                        "task_id": "T-1"}, "t1")
        issue = created(connection, "issue.create", {"title": "Known", "severity": "P2",
                                                     "evidence": "seen"}, "issue")
        # A task id names its epic, not its kind: it is looked up, and links.
        run(connection, "link.create", {"source": "demo-001", "target": issue, "type": "fixes"}, "kebab")
        assert {"type": "fixes", "target": issue} in fields(connection, "task", "demo-001")["links"]
        with pytest.raises(KeyError, match="not found"):
            run(connection, "link.create", {"source": "nothing-001", "target": issue, "type": "fixes"}, "unknown")
        with pytest.raises(ValueError, match="cannot go from"):
            run(connection, "link.create", {"source": issue, "target": "T-1", "type": "duplicate_of"}, "domain")
        with pytest.raises(KeyError, match="not found"):
            run(connection, "link.create", {"source": "T-1", "target": "T-9", "type": "relates_to"}, "absent")


def test_auto_link_adds_references_for_inline_mentions_and_skips_unknown_targets(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        issue = created(connection, "issue.create", {"title": "Known", "severity": "P2",
                                                     "evidence": "seen"}, "issue")
        run(connection, "task.update", {"id": "demo-001", "field": "notes",
                                        "value": f"Follows {issue} and ISS-404"}, "notes")
        assert fields(connection, "task", "demo-001")["links"] == [{"type": "references", "target": issue}]
        assert fields(connection, "issue", issue)["links"] == [{"type": "referenced_by", "target": "demo-001"}]


# ── Handover task membership ────────────────────────────────────────────────


def test_handover_task_membership_is_a_typed_relation(workspace):
    """`task_ids` is the field every handover carries; declaring `tasks` sent it
    to the extension bag, so the membership table stayed empty and nothing could
    ask which handovers reference a task."""
    from taskmaster.native import schema
    assert schema.owner("handover", "task_ids") == "memberships"
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        handover = created(connection, "handover.create",
                           {"tldr": "Covers demo-001", "task_ids": ["demo-001"]}, "handover")
        rows = connection.execute(
            "SELECT c.public_id,m.target_kind,m.target_id FROM memberships m "
            "JOIN entity_core c ON c.entity_key=m.entity_key "
            "WHERE m.field='task_ids' AND c.kind='handover' AND c.public_id=?", (handover,)).fetchall()
        assert rows == [(handover, "task", "demo-001")]
        # The backfilled fixture handover carries its own membership rows, so the
        # relocation covers imported documents and not just newly created ones.
        assert connection.execute(
            "SELECT COUNT(*) FROM memberships m JOIN entity_core c ON c.entity_key=m.entity_key "
            "WHERE m.field='task_ids' AND c.public_id='H-1'").fetchone()[0] == 2
        with Repository(connection).snapshot() as query:
            assert query.relations("handover", handover, field="task_ids")["items"][0]["resolved"]
            referencing = query.references_to("task", "demo-001")["items"]
            assert any(row["kind"] == "handover" and row["id"] == handover for row in referencing)


def test_completing_a_task_does_not_scan_every_handover(workspace):
    """Smart-close reads the membership index, so its cost follows the handovers
    that name the task, not the size of the handovers directory."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        handover = created(connection, "handover.create",
                           {"tldr": "Covers demo-001", "task_ids": ["demo-001"],
                            "session_kind": "task-complete"}, "related")
        run(connection, "task.pick", {"id": "demo-001", "session": "alpha"}, "claim")
        express(connection, "demo-001", "scan")
        for index in range(6):
            run(connection, "handover.create", {"tldr": f"Unrelated context {index}",
                                                "task_ids": ["demo-002"]}, f"noise-{index}")
        statements = []
        connection.set_trace_callback(statements.append)
        run(connection, "task.complete", {"id": "demo-001"}, "done")
        connection.set_trace_callback(None)
        # The paginated list over every handover is the scan the membership
        # index exists to replace; its ordering clause is its signature.
        scans = [text for text in statements if "ORDER BY c.kind,c.public_id" in text]
        assert scans == [], scans
        lookups = [text for text in statements if "FROM memberships" in text]
        assert lookups, "smart-close did not consult the membership index"
        assert fields(connection, "handover", handover)["status"] == "closed"


# ── Settings, threads and the Linear outbox ─────────────────────────────────


def test_area_updates_validate_through_the_pure_area_rules(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "area.update", {"id": "viewer", "field": "anchors",
                                        "value": json.dumps(["viewer/**"])}, "anchors")
        assert fields(connection, "area", "viewer")["anchors"] == ["viewer/**"]
        with pytest.raises(ValueError, match="JSON array"):
            run(connection, "area.update", {"id": "viewer", "field": "anchors", "value": "viewer/**"}, "bad")


def test_thread_status_overrides_land_on_the_backlog_entity(workspace):
    """The row is the store's `__backlog__`, and the thread must exist among the
    live handovers — the registry is derived from them, not trusted as stored."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "handover.create", {"tldr": "Threaded", "thread": "t"}, "threaded")
        run(connection, "thread.update", {"name": "t", "status": "parked", "reason": "waiting"}, "park")
        stored = fields(connection, "backlog", "__backlog__")
        assert stored["threads"]["t"]["status"] == "parked"
        assert stored["thread_meta"]["t"]["reason"] == "waiting"
        with pytest.raises(KeyError):
            run(connection, "thread.update", {"name": "absent", "status": "closed"}, "missing")


MANIFEST = {"schema_version": 1, "meta": {"name": "Demo", "slug": "demo", "kind": "app"}}


def test_project_settings_create_then_replace_through_one_owner(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "project.set", {"document": MANIFEST}, "create")
        assert fields(connection, "project", "__project__")["meta"]["name"] == "Demo"
        renamed = {**MANIFEST, "meta": {**MANIFEST["meta"], "name": "Renamed"}}
        run(connection, "project.set", {"document": renamed}, "replace")
        assert fields(connection, "project", "__project__")["meta"]["name"] == "Renamed"
        jobs = connection.execute("SELECT DISTINCT file FROM projection_jobs WHERE file LIKE '%project%'").fetchall()
        assert jobs == [("project.yaml",)]


def test_project_initialization_refuses_to_overwrite_an_existing_manifest(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "project.set", {"document": MANIFEST, "create_only": True}, "init")
        with pytest.raises(ValueError, match="refusing to overwrite"):
            run(connection, "project.set", {"document": {**MANIFEST, "meta": {**MANIFEST["meta"], "name": "Other"}},
                                            "create_only": True}, "again")
        assert fields(connection, "project", "__project__")["meta"]["name"] == "Demo"


@pytest.mark.parametrize("document", [
    {"schema_version": "not-a-number", "meta": 42, "repos": "nope"},
    {"meta": {"name": "Demo", "slug": "demo"}},                       # no schema_version
    {"schema_version": 1, "meta": {"name": "Demo"}},                  # no slug
    {"schema_version": 1, "meta": {"name": "Demo", "slug": "demo"},
     "repos": [{"name": "a"}]},                                       # repo without a path
])
def test_project_settings_refuse_a_manifest_the_loader_cannot_parse(workspace, document):
    """A committed manifest becomes project.yaml; one the loader cannot read
    would be written by a call that reported success."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        statements = []
        connection.set_trace_callback(statements.append)
        with pytest.raises(ValueError):
            run(connection, "project.set", {"document": document}, "invalid")
        connection.set_trace_callback(None)
        assert statements == []   # refused at admission, before any database work
        with pytest.raises(KeyError):
            fields(connection, "project", "__project__")


def test_linking_linear_creates_a_tracker_and_task_edits_enqueue_exactly_one_push(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "linear.link", {"task_id": "demo-001", "external_key": "ENG-42",
                                        "workspace_alias": "primary"}, "link")
        tracker = fields(connection, "task", "demo-001")["tracker_id"]
        assert tracker == "linear-primary-eng-42"
        assert fields(connection, "tracker", tracker)["external_key"] == "ENG-42"
        run(connection, "task.update", {"id": "demo-001", "field": "title", "value": "Renamed"}, "rename")
        run(connection, "task.update", {"id": "demo-001", "field": "notes", "value": "More"}, "notes")
        assert _queued(connection, "demo-001") == [("task_upsert", "demo-001", tracker, "pending")]
        with pytest.raises(ValueError, match="unlink first"):
            run(connection, "linear.link", {"task_id": "demo-001", "external_key": "ENG-43",
                                            "workspace_alias": "primary"}, "relink")


def test_unlinking_is_idempotent_and_stops_the_outbox(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "linear.link", {"task_id": "demo-002", "external_key": "ENG-9",
                                        "workspace_alias": "primary"}, "link")
        run(connection, "linear.unlink", {"task_id": "demo-002"}, "unlink")
        result = run(connection, "linear.unlink", {"task_id": "demo-002"}, "again")
        assert result["affected"] == []
        run(connection, "task.update", {"id": "demo-002", "field": "title", "value": "Quiet"}, "rename")
        assert _queued(connection, "demo-002") == []


def test_archiving_an_epic_queues_no_linear_push_for_the_cascade(workspace):
    """The dedicated archive tool enqueues; the epic cascade never does. A
    200-task epic would otherwise queue 200 pushes against a real workspace
    from an operation the operator expects to be local."""
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "linear.link", {"task_id": "demo-001", "external_key": "ENG-7",
                                        "workspace_alias": "primary"}, "link")
        run(connection, "epic.archive", {"id": "demo", "reason": "done"}, "archive")
        assert _queued(connection, "demo-001") == []
        with Repository(connection).snapshot() as query:
            assert query.get("task", "demo-001")["archived"]


def test_advancing_a_phase_queues_no_linear_push_for_the_tasks_it_archives(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "linear.link", {"task_id": "demo-001", "external_key": "ENG-8",
                                        "workspace_alias": "primary"}, "link")
        run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "in-progress"}, "start")
        express(connection, "demo-001", "advance")
        run(connection, "task.update", {"id": "demo-001", "field": "status", "value": "done"}, "finish")
        connection.execute("DELETE FROM linear_queue WHERE target_id='demo-001'")
        run(connection, "phase.advance", {"force": True}, "advance")
        assert _queued(connection, "demo-001") == []
        with Repository(connection).snapshot() as query:
            assert query.get("task", "demo-001")["archived"]


# The legacy derived graph tables, matched on writes only: reading the native
# `declared_links` relation is ordinary field assembly, not graph maintenance.
GRAPH_WRITE = re.compile(r"(?:INSERT INTO|DELETE FROM|UPDATE)\s+(?:related|links|entity_paths|handover_tasks)\b",
                         re.IGNORECASE)


def test_an_unsynced_task_edit_queues_nothing_and_rebuilds_no_graph(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        statements = []
        connection.set_trace_callback(statements.append)
        result = run(connection, "task.update", {"id": "demo-002", "field": "title", "value": "Retitled"}, "rename")
        connection.set_trace_callback(None)
        assert _queued(connection, "demo-002") == []
        assert result["work"]["path_comparisons"] == 0
        assert result["work"]["link_pairs"] == 0
        # The counters report work done; this proves the work was never issued.
        touched = [text for text in statements if GRAPH_WRITE.search(text)]
        assert touched == [], touched


def test_a_rolled_back_composite_leaves_no_queued_push(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        run(connection, "linear.link", {"task_id": "demo-001", "external_key": "ENG-1",
                                        "workspace_alias": "primary"}, "link")
        with pytest.raises(ValueError):
            run(connection, "batch", {"commands": [
                {"operation": "task.update", "arguments": {"id": "demo-001", "field": "title", "value": "Kept?"}},
                {"operation": "task.update", "arguments": {"id": "demo-001", "field": "status", "value": "nonsense"}},
            ]}, "batch")
        assert _queued(connection, "demo-001") == []
        assert fields(connection, "task", "demo-001")["title"] == "First"


# ── Batches over the ported families ────────────────────────────────────────


def test_a_batch_of_lifecycle_commands_commits_once_or_not_at_all(workspace):
    with closing(sqlite3.connect(workspace, isolation_level=None)) as connection:
        receipt = run(connection, "batch", {"commands": [
            {"operation": "task.pick", "arguments": {"id": "demo-001", "session": "alpha"}},
            {"operation": "task.pick", "arguments": {"id": "demo-002", "session": "alpha"}},
            {"operation": "epic.update", "arguments": {"id": "demo", "field": "status", "value": "active"}},
        ]}, "batch")
        assert {row["id"] for row in receipt["affected"]} == {"demo-001", "demo-002", "demo"}
        assert connection.execute("SELECT COUNT(*) FROM command_commits WHERE operation='batch'").fetchone()[0] == 1
        with pytest.raises(KeyError):
            run(connection, "batch", {"commands": [
                {"operation": "task.update", "arguments": {"id": "demo-002", "field": "title", "value": "Kept?"}},
                {"operation": "task.archive", "arguments": {"id": "demo-404", "reason": "duplicate"}},
            ]}, "half")
        assert fields(connection, "task", "demo-002")["title"] == "Second"


# ── Inventory coverage ──────────────────────────────────────────────────────

# Every mutating N02 tool and its native operation(s). Deferred entries name the
# milestone that owns them; an unmapped mutator fails the coverage test below.
NATIVE_MAPPING = {
    "backlog_add_task": ["task.create"],
    "backlog_update_task": ["task.update", "task.patch"],
    "backlog_pick_task": ["task.pick"],
    "backlog_complete_task": ["task.complete"],
    "backlog_archive_task": ["task.archive"],
    "backlog_record_gate": ["task.gate"],
    "backlog_skip_gate": ["task.gate_skip"],
    "backlog_clear_gate": ["task.gate_clear"],
    "backlog_record_merge": ["task.merge"],
    "backlog_set_spec_review": ["task.spec_review"],
    "backlog_clear_spec_review": ["task.spec_review_clear"],
    "backlog_add_epic": ["epic.create"],
    "backlog_update_epic": ["epic.update"],
    "backlog_archive_epic": ["epic.archive"],
    "backlog_add_phase": ["phase.create"],
    "backlog_update_phase": ["phase.update"],
    "backlog_advance_phase": ["phase.advance"],
    "backlog_batch_update": ["batch"],
    "backlog_bug_create": ["bug.create"],
    "backlog_bug_update": ["bug.update"],
    "backlog_bug_archive": ["bug.archive"],
    "backlog_bug_promote": ["bug.promote"],
    "backlog_issue_create": ["issue.create"],
    "backlog_issue_update": ["issue.update"],
    "backlog_idea_create": ["idea.create"],
    "backlog_idea_update": ["idea.update"],
    "backlog_decision_create": ["decision.create"],
    "backlog_decision": ["decision.create", "decision.resolve", "decision.drop"],
    "backlog_document_import": ["document.import"],
    "backlog_note": ["note.create", "note.update", "note.archive"],
    "backlog_link": ["link.create", "link.remove"],
    "backlog_handover_create": ["handover.create"],
    "backlog_handover_supersede": ["handover.supersede"],
    "backlog_handover_update_status": ["handover.status"],
    "backlog_thread_update": ["thread.update"],
    "backlog_area_create": ["area.create"],
    "backlog_area_update": ["area.update"],
    "backlog_project_init": ["project.set"],
    "backlog_project_set": ["project.set"],
    "backlog_linear": ["linear.link", "linear.unlink"],
    "backlog_claim": ["task.claim_renew", "task.claim_release"],
    # N13 step 7: resync imports the documents through the coordinator's sync barrier.
    "backlog_handover_resync": ["sync.begin", "sync.apply", "sync.finish"],
    "backlog_issue_resync": ["sync.begin", "sync.apply", "sync.finish"],
    # N17: the explicit import of hand edits is the same coordinator sync barrier.
    "backlog_sync": ["sync.begin", "sync.apply", "sync.finish"],
    # N14 step 6: `rebuild=True` on a native store is the graph repair.
    "backlog_index_status": ["graph.repair"],
}
DEFERRED = {
    # Maintenance and migration tools own the whole store, not one entity; they
    # stay on the legacy writer until the N15 migration rehearsal.
    "backlog_init": "N15", "backlog_migrate_v3": "N15", "backlog_migrate_v4": "N15",
    "backlog_canonicalize_layout": "N15", "backlog_backfill_lanes": "N15",
    "backlog_validate": "N15",
    # Resolving a file flagged because it and the store both changed (6.0.3,
    # B-089) is projection reconciliation, owned by the N11 outbox.
    "backlog_resolve_conflict": "N11",
    # Host actions never touch entity state.
    "backlog_open_viewer": "host", "viewer_prefs_set": "host",
}


def test_every_n02_mutating_tool_maps_onto_a_native_operation():
    from taskmaster.native import lifecycle
    inventory = json.loads((Path(__file__).resolve().parent
                            / "fixtures/native_contracts.json").read_text(encoding="utf-8"))
    mutating = {name for name, entry in inventory["tools"].items()
                if entry["transactional"] or entry["category"] in
                ("composite-command", "simple-command", "action-router", "synchronization", "maintenance")
                or name in ("backlog_open_viewer", "viewer_prefs_set")}
    unmapped = mutating - set(NATIVE_MAPPING) - set(DEFERRED)
    assert not unmapped, f"unmapped N02 mutators: {sorted(unmapped)}"
    supported = lifecycle.OPERATIONS | {"task.patch", "note.create", "batch"}
    for tool, operations in NATIVE_MAPPING.items():
        missing = set(operations) - supported
        assert not missing, f"{tool} maps onto operations the core does not accept: {sorted(missing)}"


def test_the_native_core_never_imports_a_remote_client():
    package = Path(__file__).resolve().parents[1] / "taskmaster/native"
    for module in sorted(package.glob("*.py")):
        tree = ast.parse(module.read_text(encoding="utf-8"))
        names = {node.module or "" for node in ast.walk(tree) if isinstance(node, ast.ImportFrom)}
        names |= {alias.name for node in ast.walk(tree) if isinstance(node, ast.Import)
                  for alias in node.names}
        forbidden = {name for name in names
                     if name.split(".")[0] in ("httpx", "requests", "urllib", "http", "socket")
                     or name.startswith("taskmaster.integrations")}
        assert not forbidden, f"{module.name} reaches a remote client: {sorted(forbidden)}"
